### ISSUE TITLE
moment coefficient의 계산 문제

### ISSUE THREAD

**Issue by HaminChang** [Youngjun-Lee-FDCL/aic-issue-only#6]
[v0.0.0 기준]

일전에 한번 드렸던 질문이긴 한데, 다시 한번 정리해서 드리고자 합니다.
현재 시뮬레이터에서 moment coefficient C_l의 계산은 다음과 같은 두 가지 방법으로 가능합니다.

1) cl_a, cl_p, cl_dp에 대해 정리된 다음의 식을 활용하는 방법
![image](https://user-images.githubusercontent.com/103189212/162657971-c950d835-335e-4118-8cfb-a454fea45cf7.png)

2) angular acceleration으로부터 역산하는 방법
pdot. * (Ixx ./ (Sref * Lref * Q))

이러한 두 가지 방법으로 계산한 C_l의 결과를 각각 Cl1, Cl2라 하고 이를 time step에 대해 플로팅해보면
다음과 같은 그림을 얻을 수 있습니다.

![untitled](https://user-images.githubusercontent.com/103189212/162659364-a6f17932-cc11-4416-8c2a-a04bad879653.png)

이론적으로 그림에서 두 그래프는 같은 궤적을 그려야할 것으로 보이는데,
두 그래프 사이의 차이는 왜 발생하며, 어떻게 받아들이는 것이 좋을까요?  
Ex) 시뮬레이터의 세상에서 사는 사람은 Cl1이 결정되는 식을 알 수 없기 때문에
정확한 Cl1의 궤적은 알 수 없고, Cl2로 역산한 결과를 통해 Cl1을 추정해야 한다.

감사합니다.

PS)

다음의 코드를 run_6d_stepCmd.m의 마지막에 추가하신 뒤 돌려보시면 같은 그림을 얻으실 수 있습니다.
(uncertainty 등은 모두 없는 상태를 전제하고 있습니다.)
%--------------------------------------------------------------------------------
%% Aerocoefficient Cl
close all;
cla = log.missile6dof.aero_coeff.data(:,1);
clp = log.missile6dof.aero_coeff.data(:,2);
cldp = log.missile6dof.aero_coeff.data(:,3);

% Constants and data
Lref = 0.1524;
Sref = 0.01824;
rho = 1.1116;
r2d = 180/pi;

p = log.missile6dof.angular_rate.data(:,1);
delp = log.missile6dof.delta_pqr.data(:,1);
alpha = log.missile6dof.total_AOA.data(:,1);
beta = log.missile6dof.total_AOA.data(:,2);
VT = log.missile6dof.speed.data;
Q = 0.5 * rho * (VT.^2);
% M = log.missile6dof.mach.data;
Ixx = log.missile6dof.airframe.data(:,3);
pdot = r2d * log.missile6dof.angular_acc.data(:,1); % [deg/s^2]

%% Double counting for Cl
Cl1 = cla.*sin(4*beta).*(alpha.^2) + clp.*(Lref*(p*r2d)./(2*VT)) + cldp.*delp;
Cl2 = pdot.*(Ixx./(Sref*Lref*Q));
xAxis = 1:length(Cl1);
plot(xAxis, Cl1, xAxis, Cl2);
grid on;
legend('Cl1', 'Cl2');
%--------------------------------------------------------------------------------

**Comment by Youngjun-Lee-FDCL** [comment]
우선 밀도값이 고도에 따라 변하며 이에따라 Q의 계산이 시간에 따라 달라질 수 있겠습니다. 밀도값을 저장해보시거나 혹은 Q값을 저장하여 비교해보시는것을 추천드립니다. 이 방법을 쓰더라도 두 값이 같지 않을경우 다시 말씀 부탁드립니다.

**Comment by HaminChang** [comment]
밀도 값의 변화가 크지 않아서 그것이 dominant한 이유는 아닌 듯 합니다.
아래와 같이 고도에 따라 변하는 밀도 값의 변화를 Q의 계산에 반영하는 코드를 사용하였습니다.

혹시 \dot{p}를 계산하는 과정이나 discretized model에 의한 영향은 없을까요?
%--------------------------------------------------------------------------------
%% Aerocoefficient Cl
cla = log.missile6dof.aero_coeff.data(:,1);
clp = log.missile6dof.aero_coeff.data(:,2);
cldp = log.missile6dof.aero_coeff.data(:,3);

% Constants and data
Lref = 0.1524;
Sref = 0.01824;
% rho = 1.1116;
r2d = 180/pi;
gasConstant = 287.053;
airPressure = 101325;

alt = log.missile6dof.pos.data(:,3);
T = 288.15 - 0.0065 * alt;
P = airPressure * (T / 288.15 ).^5.2559;
rho = P ./ ( gasConstant * T);

p = log.missile6dof.angular_rate.data(:,1);
delp = log.missile6dof.delta_pqr.data(:,1);
alpha = log.missile6dof.total_AOA.data(:,1);
beta = log.missile6dof.total_AOA.data(:,2);
VT = log.missile6dof.speed.data;
Q = 0.5 * rho .* (VT.^2);
% M = log.missile6dof.mach.data;
Ixx = log.missile6dof.airframe.data(:,3);
pdot = r2d * log.missile6dof.angular_acc.data(:,1); % [deg/s^2]

%% Double counting for Cl
Cl1 = cla.*sin(4*beta).*(alpha.^2) + clp.*(Lref*(p*r2d)./(2*VT)) + cldp.*delp;
Cl2 = pdot.*(Ixx./(Sref*Lref*Q));
xAxis = 1:length(Cl1);
plot(xAxis, Cl1, xAxis, Cl2);
grid on;
legend('Cl1', 'Cl2');
%--------------------------------------------------------------------------------

**Comment by Miracle-Penguin** [comment]
aerodynamic_SRAAM.m에서 계산되는 cll 변수와 올려주신 코드의 Cl2 변수에 대해 Cl2/r2d를 plot한 결과가 아래와 같습니다.

![image](https://user-images.githubusercontent.com/54303840/162879792-2bb0ced3-f601-4920-8ee3-40842f0fed7f.png)

그림에서 볼 수 있듯이 두 변수가 동일한데, 이로부터 아마 Cl1 계산과정에 오류가 있지 않나 생각합니다.

**Comment by HaminChang** [comment]
넵, 말씀 주신대로 아예 aerodynamic_SRAAM.m에서 계산되는 cll 변수를 꺼내와서 보니 코드의 Cl2/r2d와 같게 나옵니다. 앞으로도 최대한 aerodynamic_SRAAM.m에서 직접 데이터를 꺼내는 방식으로 해보려고 합니다. 신경 써 주셔서 감사합니다!

**Comment by parkjo05** [comment]
장하민 연구원님. 안녕하세요.
오늘 발표 너무 잘 들었습니다.

Cl1에 사용하는 alpha와 beta는 log.missile6dof.total_AOA.data 로부터 오는데 
이를 Missile6dofStepInputSystem 에서 찾아보면 line 127의 
obj.log.total_AOA.append(rad2deg([M.totalAoA, M.totalPhi])); 이 녀석을 이용해서 log를 쌓는 것 같습니다.

그런데 aerodynamic_SRAAM.m을 가보면, Cl1과 동일한 계산 수식인 line 120~121을 확인해보시면
alpha_t는 deg. 단위가 맞는데 --> line 76에서 rad2deg 해줌
phi_t 단위는 rad. 단위로 보입니다. --> line 75에서 rad으로 나옴 (왜냐하면 line 169, 172에서 atan2의 output임)

즉, phi_t의 단위가 맞지 않는 것으로 보이는데
한번 확인해보시길 바랍니다.

**Comment by parkjo05** [comment]
obj.log.angular_rate.append(rad2deg(M.angularVel.')); 의 p 값도 rad2deg로 변환되어 log에 쌓이는 것으로 보이는데,
Cl1 수식을 보면 p에 다시 한번 r2d가 곱해지고 있습니다. -> p*r2d

aerodynamic_SRAAM.m에서는 p가 rad이고 수식 내에 (Cl1 수식과 마찬가지로) r2d가 있습니다.
aerodynamic_SRAAM.m line 121 : cllp * ( p * r2d ) * obj.refLength / ( 2 * Vm )

즉, 현재 Cl1 수식을 사용하려면 p의 단위를 radian으로 통일해야 하지 않을까요

**Comment by HaminChang** [comment]
네, 박종호 교수님!
그렇지 않아도 단위 문제로 생각하고 있었는데 친절히 답변해 주셔서 감사합니다.
그리고 기초적인 실수로 신경 쓰시게 해드려 죄송합니다 :(

말씀주신대로 p값은 rad2deg로 변환되어 쌓이는 것이 맞고, 결과적으로 log에 저장된 p값은 deg 단위인 것으로 보입니다.
마찬가지로 phi_t의 경우 log에 저장된 값은 deg 단위이기 때문에 radian으로 변환해야 하고
결과적으로 다음과 같이 Cl1을 계산하는 것이 맞습니다.

![image](https://user-images.githubusercontent.com/103189212/162933937-679f6a52-96cc-4b71-a20c-25cba643f7fa.png)

**Comment by parkjo05** [comment]
상기 수정으로 이제 Cl1과 Cl2가 같은 값이 나오나요?

**Comment by HaminChang** [comment]
네 그렇습니다. 다음과 같이 동일한 Cl1과 Cl2를 얻을 수 있었습니다!
혹시 몰라 나스 저장소에 관련 코드를 업로드 해두겠습니다.

감사합니다 :)

![image](https://user-images.githubusercontent.com/103189212/162938305-189ed9e8-6b04-4d02-9a75-dfab84852a93.png)

**Comment by parkjo05** [comment]
빨리 해결되어서 다행이네요.

장하민 연구원님.
(매우 사소한 것이지만)
앞으로는 notation은 최대한 통일하면 좋을 것 같습니다. Cl1 수식이
Cl1 = cla.*sin(4*beta).*(alpha.^2) + clp.*(Lref*(p*r2d)./(2*VT)) + cldp.*delp; 이렇게 되어 있는데,
alpha 대신 alpha_tot , beta 대신 phi_tot 등으로 최대한 통일하는 것이 다른 사람들이 보기에 헷갈리지 않을 것 같습니다.
여러 명이서 같은 코드로 프로젝트 진행할때 notation 통일이 생각보다 중요하더라고요 ㅎㅎ

**Comment by HaminChang** [comment]
네 교수님, 사소하지 않고 너무 좋습니다. 앞으로는 통일된 노테이션을 사용하도록 하겠습니다.

total angle of alpha -> alpha_tot
total bank angle -> phi_tot         로 표기하겠습니다!
